module.exports = {
  development: {
    username: 'root',
    password: null,
    database: 'telegram-bot-development',
    timezone: '+00:00',
    host: '127.0.0.1',
    dialect: 'mysql',
    logging: false,
    define: {
      charset: 'utf8mb4',
      collate: 'utf8mb4_unicode_ci',
      freezeTableName: true,
      underscored: true,
    },
    use_env_variable: false,
  },
  test: {
    username: 'root',
    password: null,
    database: 'telegram-bot-test',
    timezone: '+00:00',
    host: '127.0.0.1',
    dialect: 'mysql',
    logging: false,
    define: {
      charset: 'utf8mb4',
      collate: 'utf8mb4_unicode_ci',
      freezeTableName: true,
      underscored: true,
    },
    use_env_variable: false,
  },
  production: {
    username: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASS,
    database: process.env.DATABASE_NAME,
    timezone: process.env.DATABASE_TIME,
    host: process.env.DATABASE_HOST,
    dialect: process.env.DATABASE_DIALECT,
    logging: false,
    define: {
      charset: 'utf8mb4',
      collate: 'utf8mb4_unicode_ci',
      freezeTableName: true,
      underscored: true,
    },
    use_env_variable: false,
  },
};
